# -*- coding: utf-8 -*-
"""Project_data_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AanN9mir3qqEdGFtp-UzcUpGA6qCu3hX
"""

import pandas as pd
import requests
import json
import plotly.express as plx
dat = pd.read_csv('df_from_2010_to_2023.csv', index_col=0)
df_values_2024=pd.read_csv('df_2024.csv', index_col=0)

df_values_2024=df_values.rename(columns={"CBSA": "GTCBSA"})
df_values_2024['year']=2024

df = pd.concat([dat, df_values_2024])

dummy_var=pd.get_dummies(dat[['PEDISDRS', 'PEDISEAR', 'PEDISEYE', 'PEDISOUT', 'PEDISPHY', 'PEDISREM']]).astype(int)

df_with_dummy = pd.concat([dat, dummy_var], axis=1)

df_with_dummy = df_with_dummy.rename(columns={"CBSA": "GTCBSA"})

#By rent
df_by_rent = df_with_dummy.groupby(["state", "GTCBSA", "year", 'HETENURE'])[dummy_var.columns].sum()
df_by_rent.reset_index(inplace=True)
melt_rent_data=df_by_rent.melt(id_vars=["state", "GTCBSA", "year", 'HETENURE'])

#By members
df_by_members = df_with_dummy.groupby(["state", "GTCBSA", "year", 'HRNUMHOU'])[dummy_var.columns].sum()
df_by_members.reset_index(inplace=True)
melt_members_data=df_by_members.melt(id_vars=["state", "GTCBSA", "year", 'HRNUMHOU'])

#By Type
df_by_type = df_with_dummy.groupby(["state", "GTCBSA", "year", 'HRHTYPE'])[dummy_var.columns].sum()
df_by_type.reset_index(inplace=True)
melt_type_data=df_by_type.melt(id_vars=["state", "GTCBSA", "year", 'HRHTYPE'])

type_data=type_data[type_data["variable"].str.contains("Yes")]

members_data=members_data[members_data["variable"].str.contains("Yes")]

rent_data=rent_data[rent_data["variable"].str.contains("Yes")]

type_data.to_csv("type_data.csv")
members_data.to_csv("members_data.csv")
rent_data.to_csv("rent_data.csv")

from google.colab import files
files.download("type_data.csv")
files.download("members_data.csv")
files.download("rent_data.csv")